config/routes.rb
Omrails::Application.routes.draw do
  get 'tag/:tag', to: 'pins#index', as: :tag
  get "users/show"

  resources :pins

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'

  get 'users' => 'pages#users'

  
  root :to => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url 
  acts_as_taggable 
  acts_as_taggable_on :pins, :tag_list


  
  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true, 
  										 				 content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']  },
  														 size: { less_than: 5.megabytes }

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}


  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super

  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

 def users
 end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
   if params[:tag]
     @pins = Pin.order("created_at desc").page(params[:page]).per_page(4).tagged_with(params[:tag])
    else
       @pins = Pin.order("created_at desc").page(params[:page]).per_page(4)
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

   @pin.description = params[:pin][:description]
    @pin.tag_list = params[:pin][:tag_list]

      respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
 		@users = user.page(params[:page]).per_page(3)
 	end

  def show
  	@user = User.find(params[:id])
  	@pins = @user.pins.page(params[:page]).per_page(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
			    
		    <small>
		    	<%= link_to "Ekaitztter", "http://onemonthrails.com" %>
		    	by <%= link_to "Ekaitz Solabarrieta", "http://mattangriffel.com" %>
		    </small>

		     
		</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
     
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </a>
     
    <!-- Be sure to leave the brand out there if you want it shown -->
    
    <%= link_to "Ekaitztter", root_path, class: "brand" %>
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
      <ul class="nav">
	   	 <li><%= link_to "  Home ", root_path %></li>
		 <li><%= link_to " About  ", about_path %></li>
         <li><%= link_to " Users ", users_path %></li>


         
	  </ul>
	  <ul class="nav pull-right">
         <% if user_signed_in? %>
         <li> User: <%= current_user.name %> </li>
         <li><%= link_to "Add +", new_pin_path %></li>
         <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
         
         
	   	 <li><%= link_to "Logout",  destroy_user_session_path, method: :delete %></li>

         <% else %>
         <li><%= link_to "Login", new_user_session_path %></li>
         <% end %>
	  </ul>

    <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#999">
        Proving
        <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
        <!-- dropdown menu links --><li><%= link_to "Edit Profile", edit_user_registration_path %></li>
         <li class="divider"></li>
        
           
        <li class="active"><a href="#"><i class="icon-home icon-white"></i> Home</a></li>
            <li class="divider"></li>
            <li><a href="#"><i class="icon-camera"></i> New photo</a></li>
            <li class="divider"></li>
            <li class="active"><a href="#"><i class="icon-remove"></i> Delete photo</a></li>
            <li class="divider"></li>
            <li><a href="#"><i class="icon-tags"></i> Tag photo</a></li>
        </ul
       
        </ul>
    </div>

    </div>
     
    </div>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Ekaitztter!</title>
	  
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		
  		<div class="container">
  			<% flash.each do |name, msg| %>
  				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>

	</body>
</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>
<div class="hero-unit" href="#999">
	<h1>Welcome to Ekaitztter!</h1>
	<p>
		You've found the home page for the 
		<%= link_to "Ekaitztter", "http://thawing-retreat-1897.herokuapp.com/" %>
		application.
	</p>
	<p>
		<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	You can put all kind of pictures you want.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <h1> You're logged in! </h1>
<% else %>
<div class="hero-unit">
	<h1>Welcome to One Month Rails!</h1>
	<p>
		You've found the home page for the 
		<%= link_to "One Month Rails", "http://onemonthrails.com" %>
		application.
	</p>
	<p>
		<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image , label: "Upload an image" %>
  <%= f.input :image_remote_url , label: "or enter URL" %>
  <%= f.input :description, as: :text, input_html: { rows: "3"} %>
  <%= f.input :tag_list, as: :text, input_html: {rows: "1"} %>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p class="description">
		<%= pin.description %>
	</p>

	<p>
		<strong>
			Posted by <%= link_to pin.user.name, pin.user unless pin.user.nil? %>
		</strong>
	</p>
	<p> Tags: <%= raw pin.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')  %>
	</p>

	<% if current_user == pin.user %>
	      <p>
		      <%= link_to 'Edit', edit_pin_path(pin) %>
		      <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		      
		     
				</p>
	<% end %>


	
</div>

app/views/pins/comment.html.erb
<h1>Comment</h1>

<%= render 'form' %>

<%= link_to 'Write', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
 
</div>

<%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
  $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="span6 offset3">
  	<div class="well">
      <%= image_tag @pin.image %>
      <p>
        <%= @pin.description %>
      </p>
      <p>
         Posted by <%= @pin.user.name %>
      </p>
      <% if current_user == @pin.user %>

     <a href="#"><i class="icon-comment"></i> Comment photo </a>
     <p><a href="#"><i class="icon-thumbs-up"></i>  </a>
     <a href="#"><i class="icon-thumbs-down"></i>  </a></p>
      <% end %>
      <%= link_to 'Back', pins_path %>
    <p>
      <%= link_to 'Comment photo' %>
    </p>
  
   </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="box user">
<%= gravatar_image_tag(user.email, :gravatar => { :size => 150 }) %>
<p class="user-name"><%= link_to user.name, user %></p>
</div>

app/views/users/index.html.erb
<%= render 'pages/home' %>
<div class="row-fluid users">
<%= render @users %>
</div>

<%= will_paginate @user %>

app/views/users/show.html.erb
<div class="row-fluid profile-card">
<div class="span4">
<%= gravatar_image_tag(@user.email, class: "profile-image", :gravatar => { :size => 100 }) %>
</div>
<div class="span6 push2">
<h1 class="profile-name"><%= @user.name %></h1>
<p><i class="icon-pushpin"></i><%= @user.pins.count %> pins</p>
<p><i class="icon-user"></i>Member since <%= @user.created_at.strftime("%Y") %>
</p>
</div>
</div>

<div class="row-fluid pins">
<%= render @pins %>
</div>

<%= will_paginate @pins %>